/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author CM Jinghiro
 */
public class EditDescriptionWindow extends javax.swing.JFrame {

    /**
     * Creates new form DescriptionWindow
     */
    public EditDescriptionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EDWImageLabel = new javax.swing.JLabel();
        EDWNameLabel = new javax.swing.JLabel();
        EDWAgeLabel = new javax.swing.JLabel();
        EDWLocLabel = new javax.swing.JLabel();
        EDWNameText = new javax.swing.JTextField();
        EDWAgeText = new javax.swing.JTextField();
        EDWLocationText = new javax.swing.JTextField();
        EDWPayLabel = new javax.swing.JLabel();
        EDWPaymentText = new javax.swing.JTextField();
        EDWAbtCondoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EDWTable = new javax.swing.JTable();
        EDWSaveButton = new javax.swing.JButton();
        EDWBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EDWImageLabel.setText("Image");

        EDWNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDWNameLabel.setText("Name:");

        EDWAgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDWAgeLabel.setText("Age:");

        EDWLocLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDWLocLabel.setText("Location:");

        EDWNameText.setText("Ortigas Regency");

        EDWAgeText.setText("3 Years");
        EDWAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDWAgeTextActionPerformed(evt);
            }
        });

        EDWLocationText.setText("San Antonio, Pasig City");

        EDWPayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDWPayLabel.setText("Payment Options:");

        EDWPaymentText.setText("Installment");

        EDWAbtCondoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EDWAbtCondoLabel.setText("About Condo:");

        EDWTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pets Allowed", "Fire Exits"},
                {"Open Kitchen", "Gym"},
                {"Cityland", "24-hour Security"},
                {"Semi Furnishing", "Air Conditioning"},
                {"No Balconies", null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Details", "Amenities"
            }
        ));
        jScrollPane1.setViewportView(EDWTable);

        EDWSaveButton.setText("Save");

        EDWBackButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EDWAbtCondoLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(EDWSaveButton)
                                .addGap(18, 18, 18)
                                .addComponent(EDWBackButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(EDWImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(EDWPayLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EDWPaymentText))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(EDWLocLabel)
                                                .addGap(8, 8, 8)
                                                .addComponent(EDWLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(EDWNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EDWNameText)))
                                        .addGap(29, 29, 29)
                                        .addComponent(EDWAgeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EDWAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDWNameLabel)
                            .addComponent(EDWAgeLabel)
                            .addComponent(EDWNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDWAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDWLocLabel)
                            .addComponent(EDWLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDWPayLabel)
                            .addComponent(EDWPaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(EDWImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDWAbtCondoLabel)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDWBackButton)
                    .addComponent(EDWSaveButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EDWAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDWAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDWAgeTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDescriptionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDescriptionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDescriptionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDescriptionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDescriptionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EDWAbtCondoLabel;
    private javax.swing.JLabel EDWAgeLabel;
    private javax.swing.JTextField EDWAgeText;
    private javax.swing.JButton EDWBackButton;
    private javax.swing.JLabel EDWImageLabel;
    private javax.swing.JLabel EDWLocLabel;
    private javax.swing.JTextField EDWLocationText;
    private javax.swing.JLabel EDWNameLabel;
    private javax.swing.JTextField EDWNameText;
    private javax.swing.JLabel EDWPayLabel;
    private javax.swing.JTextField EDWPaymentText;
    private javax.swing.JButton EDWSaveButton;
    private javax.swing.JTable EDWTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
