/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulm
 */
public class EditDetails extends javax.swing.JFrame {

    EditDescription _MyEditDescription = null;
    public EditDetails() {
        initComponents();
    }

    public void setDescriptionWindow(EditDescription win){
        _MyEditDescription = win;
    }
    
    public void setUpValues(ArrayList<String> data){
        DefaultTableModel detailModel = (DefaultTableModel) EDDetailTable.getModel();
        for(int j = 0; j < data.size(); ++j){
            detailModel.addRow(new String[]{data.get(j)});
        }
    }
    
    public void addAmeties(String data){
        DefaultTableModel amenitiesModel = (DefaultTableModel) EDDetailTable.getModel();
        amenitiesModel.addRow(new String[]{data});
        _MyEditDescription.pushNewDetails(data);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EDDetailTable = new javax.swing.JTable();
        EDAddButton = new javax.swing.JButton();
        EDRemoveButton = new javax.swing.JButton();
        EDOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Editing Details");

        EDDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Details"
            }
        ));
        jScrollPane1.setViewportView(EDDetailTable);

        EDAddButton.setText("Add");
        EDAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDAddButtonActionPerformed(evt);
            }
        });

        EDRemoveButton.setText("Remove");
        EDRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDRemoveButtonActionPerformed(evt);
            }
        });

        EDOkButton.setText("OK");
        EDOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(EDAddButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDOkButton)
                            .addComponent(EDRemoveButton))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EDAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDRemoveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EDOkButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EDRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDRemoveButtonActionPerformed
        int currentRow = EDDetailTable.getSelectedRow();
        DefaultTableModel tempModel = (DefaultTableModel) EDDetailTable.getModel();
        tempModel.removeRow(currentRow);
        _MyEditDescription.removeDetails(currentRow);
    }//GEN-LAST:event_EDRemoveButtonActionPerformed

    private void EDAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDAddButtonActionPerformed
        AddDetails newAdd = new AddDetails();
        newAdd.setEditDetails(this);
        newAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EDAddButtonActionPerformed

    private void EDOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDOkButtonActionPerformed
        this.setVisible(false);
        _MyEditDescription.setVisible(true);
    }//GEN-LAST:event_EDOkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDAddButton;
    private javax.swing.JTable EDDetailTable;
    private javax.swing.JButton EDOkButton;
    private javax.swing.JButton EDRemoveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
